env:
  node: true
extends:
  - 'airbnb-base'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: babel-eslint


plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel

rules:
  no-console: 0
