env:
  node: true
  jest: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: babel-eslint

parserOptions:
 sourceType: "module",
 ecmaVersion: 2018

rules:
  no-console: 0
